apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pedido-backend
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/minScale: '0'
    run.googleapis.com/max-surge: '0'
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:     
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: ci-cd-github-actions@storied-imprint-441522-s7.iam.gserviceaccount.com
      containers:
      - name: pedido
        image: us-central1-docker.pkg.dev/storied-imprint-441522-s7/gcr.io/pedido:latest
        ports:
        - name: http1
          containerPort: 31302
        env:
          - name: PROJECT_ID
            value: storied-imprint-441522-s7
          - name: REGION
            value: us-central1
          - name: VERSAO
            value: "005"
          - name: DATABASE_URL
            value: '${{ secrets.DATABASE_URL }}'
        resources:
          limits:
            cpu: '1000m'
            memory: '512Mi'
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 31302
  traffic:
  - percent: 100
    latestRevision: true